# Generated by Django 5.1 on 2024-10-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blococirurgico',
            name='enfermeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
        migrations.AddField(
            model_name='classificacaoderisco',
            name='enfermeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
        migrations.AddField(
            model_name='unidadedeinternacao',
            name='enfermeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
    ]
