# Generated by Django 5.1 on 2024-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blococirurgico',
            name='observacoes',
            field=models.TextField(default='', help_text='Caso uma ou mais cirurgias tenham sido suspensas, favor justificar a suspensão das mesmas.', max_length=127, verbose_name='Observações'),
        ),
    ]
